n1 = float(input('Digite uma distancia em metros: '))
print('a medida de {}m corresponde a'.format(n1))
print('{}km'.format(n1/1000))
print('{}hm'.format(n1/100))
print('{}dam'.format(n1/10))
print('{:.0f}dm'.format(n1*10))
print('{:.0f}cm'.format(n1*100))
print('{:.0f}mm'.format(n1*1000))
